config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('usuarios.urls_reset')),
    path('usuarios/', include('usuarios.urls')),
    path('ofertas/', include('ofertas.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    path("chaining/", include("smart_selects.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home

app_name= 'home'

urlpatterns= [
    path("", home, name="index"),
]

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title> {% block title %} Gestión Cursos {% endblock %}</title>
  <link rel="stylesheet" href="{% static 'fonts/fontawesome/css/all.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/variables.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/home/style.css' %}" />
  <!-- En el <head> para los estilos -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">

  {% block css %}{% endblock %}

  {% if css_file %}
  <link rel="stylesheet" href="{% static css_file %}">
    {% endif %}
</head>
<body class="body">
  <aside class="sidebar">
    <div class="sidebar__logo">
      <img src="{% static './img/logo_sena.png' %}" alt="Logo Sena" class="sidebar__logo-img" />
      <p class="sidebar__role"></p>
    </div>
    <nav class="sidebar__nav">
      <div class="menu-category">Principal</div>
      <a href="{% url 'home:index' %}" class="sidebar__link sidebar__link--active"><i class="fas fa-home"></i>Inicio</a>

      {% for menu in sidebar_menus %}
      <div class="menu-category">{{ menu.category }}</div>
        {% for link in menu.links %}
            <a href="{{ link.url }}" class="sidebar__link">
                <i class="{{ link.icon }}"></i>{{ link.label }}
            </a>
        {% endfor %}
      {% endfor %}

      <div class="menu-category">Configuracion</div>

      <a href="#" class="sidebar__link "><i class="fas fa-users"></i>Ajustes</a>
      <a href="#" class="sidebar__link"><i class="fas fa-book"></i>Ayuda</a>
      <a href="#" class="sidebar__link"><i class="fas fa-tasks"></i>Cerrar Sesión</a>
    </nav>
  </aside>

  <div class="dashboard">
    <div class="header">
        <div class="search-bar">
          <i class="fas fa-search"></i>
          <input type="text" placeholder="Buscar" />
        </div>
        <div class="user-menu">
          <div class="user-info">
            <div class="user-name">{{ request.user.first_name }} {{ request.user.last_name}}</div>
            <div class="user-role">{{ grupo_nombre }}</div>
          </div>
          <div class="user-avatar">
            {{ request.user.first_name|slice:":1" }}{{ request.user.last_name|slice:":1" }}
          </div>
        </div>
    </div>

    {% block content %}

    {% endblock %}

  </div>
  {% if js_file %}
  <script src="{% static js_file %}"> </script>
  {% endif %}

    <!-- Antes de cerrar el </body> para el JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>